In [134]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
from sklearn.datasets import load_wine
wine=load_wine()

In [135]:
#Features dataframe
df=pd.DataFrame(wine.data,columns=wine.feature_names)
df.head()
X=df

In [136]:
X.isnull().sum()

alcohol                         0
malic_acid                      0
ash                             0
alcalinity_of_ash               0
magnesium                       0
total_phenols                   0
flavanoids                      0
nonflavanoid_phenols            0
proanthocyanins                 0
color_intensity                 0
hue                             0
od280/od315_of_diluted_wines    0
proline                         0
dtype: int64

In [137]:
#label
y=pd.Series(wine.target,name="Target")


In [138]:
wine.target_names

array(['class_0', 'class_1', 'class_2'], dtype='<U7')

In [139]:
#feature selection
from sklearn.feature_selection import SelectKBest,chi2
sk=SelectKBest(chi2,k=10)
sk.fit(X,y)
sk.transform(X)

array([[  14.23,    1.71,   15.6 , ...,    5.64,    3.92, 1065.  ],
       [  13.2 ,    1.78,   11.2 , ...,    4.38,    3.4 , 1050.  ],
       [  13.16,    2.36,   18.6 , ...,    5.68,    3.17, 1185.  ],
       ...,
       [  13.27,    4.28,   20.  , ...,   10.2 ,    1.56,  835.  ],
       [  13.17,    2.59,   20.  , ...,    9.3 ,    1.62,  840.  ],
       [  14.13,    4.1 ,   24.5 , ...,    9.2 ,    1.6 ,  560.  ]])

In [148]:
sk.pvalues_

array([6.56938863e-02, 8.03489047e-07, 6.89567769e-01, 4.16304971e-07,
       1.66972759e-10, 4.05034646e-04, 1.76656548e-14, 4.03433989e-01,
       9.24066398e-03, 2.12488671e-24, 7.49248322e-02, 8.33587826e-06,
       0.00000000e+00])

In [152]:
X_data =X[["alcohol","ash","nonflavanoid_phenols","hue","proline"]] #selecting best features

In [153]:
X.columns

Index(['alcohol', 'malic_acid', 'ash', 'alcalinity_of_ash', 'magnesium',
       'total_phenols', 'flavanoids', 'nonflavanoid_phenols',
       'proanthocyanins', 'color_intensity', 'hue',
       'od280/od315_of_diluted_wines', 'proline'],
      dtype='object')

In [154]:
#splitting the data based on train test and split
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X_data,y,test_size=0.2,random_state=11)

In [155]:
#pipeline  needs preprocessing and models
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import ExtraTreesClassifier
my_pipeline=make_pipeline(StandardScaler(),ExtraTreesClassifier())

In [156]:
my_pipeline.fit(X_train,y_train)

C:\Users\vidya\Anaconda3\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


Pipeline(memory=None,
     steps=[('standardscaler', StandardScaler(copy=True, with_mean=True, with_std=True)), ('extratreesclassifier', ExtraTreesClassifier(bootstrap=False, class_weight=None, criterion='gini',
           max_depth=None, max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impu...ators=10, n_jobs=None,
           oob_score=False, random_state=None, verbose=0, warm_start=False))])

In [157]:
y_pred=my_pipeline.predict(X_test)
y_pred

array([2, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 2, 0, 0, 1, 1, 0, 2, 1, 1, 0, 2,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 2, 2])

In [158]:
my_pipeline.score(X_test,y_test)

0.9166666666666666

In [159]:
#checking the accuracy of model
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.9166666666666666